### ISSUE TITLE
Great project! Can you provide the BOM file of Flipper Zero Multi Board PCB? thanks

### ISSUE THREAD

**Issue by LuckyFishGeek** [IAmOrion/FlipperZeroStuff#2]
I am a novice in hardware and want to learn about soldering, so please provide the content of BOM, thank you very much

**Comment by IAmOrion** [comment]
Bill of Materials: Flipper Zero ESP NRF I2S HCSR04 GPS MultiBoard.fzz
/Volumes/NAS/Fritzing/Fritzing Sketches/Flipper Zero ESP NRF I2S HCSR04 GPS MultiBoard.fzz

Thursday, May 25 2023, 23:12:55

Assembly List
Label	MN (manufacturer number)	MPN (manufacturer part number)	Part Type	Properties
100nF			Capacitor	package 1206; variant 1206
10uF			Capacitor	package 1206; variant 1206
2.8" Touch Screen TFT ILI9341			2.8" SPI TFT Module	variant variant 1; pins 18; chip label LCD; part # MSP2807
3.3v			DIP Switch 4 Position	package dipswitch-04; variant variant 2; channels 4
3.3v I2C			Screw terminal - 4 pins	package THT; pins 4; pin spacing 0.1in (2.54mm); hole size 1.0mm,0.508mm
5v			DIP Switch 4 Position	package dipswitch-04; variant variant 2; channels 4
< TX/RX EN			DIP SWITCH	package dipswitch-02; channels 1
Adafruit GPS 746			Adafruit Ultimate GPS v3	variant variant 1; part # Adafruit #746
CS SELECT			Solder Jumper	package sj_2w; variant w
Deauth JMP >			Generic male header - 3 pins	package THT; variant variant 1; row single; form ♂ (male); pins 3; hole size 1.0mm,0.508mm; pin spacing 0.1in (2.54mm)
ESP32S 30-Pin			DOIT Esp32 DevKit v1 (30 pins long, 11 pins width)	variant 1; pins 30; part # ESP32S-PIN30
ESP8266 Deauth			DIP Switch 4 Position	package dipswitch-04; variant variant 2; channels 4
FZLEFT			Generic double row male header - 16 pins	package THT; row double; form ♂ (male); pins 16; hole size 1.0mm,0.508mm; pin spacing 0.1in (2.54mm)
FZRIGHT			Generic double row male header - 20 pins	package THT; row double; form ♂ (male); pins 20; hole size 1.0mm,0.508mm; pin spacing 0.1in (2.54mm)
GND			Generic double row male header - 6 pins	package THT; row double; form ♂ (male); pins 6; hole size 1.0mm,0.508mm; pin spacing 0.1in (2.54mm)
HC-SR04			Generic male header - 4 pins	package THT; row single; form ♂ (male); pins 4; hole size 1.0mm,0.508mm; pin spacing 0.1in (2.54mm)
LED			Red (633nm) LED	package 1206 [SMD]; color Red (633nm)
LED			Red (633nm) LED	package 1206 [SMD]; color Red (633nm)
LED			Red (633nm) LED	package 1206 [SMD]; color Red (633nm)
microSD			SparkFun - microSD Transflash	variant BOB-00544
microSD1			SparkFun - microSD Transflash	variant BOB-00544
NRF24			NRF24L01+ PA LNA	variant variant 2; chip NRF24L01+ PA LNA
RX JMP			Solder Jumper	package sj_2; variant t
RΩ			220Ω Resistor	tolerance ±5%; resistance 220Ω; package 1206 [SMD]
RΩ			220Ω Resistor	tolerance ±5%; resistance 220Ω; package 1206 [SMD]
RΩ			220Ω Resistor	tolerance ±5%; resistance 220Ω; package 1206 [SMD]
Screen Support			Generic male header - 14 pins	package THT; row single; form ♂ (male); pins 14; hole size 1.0mm,0.508mm; pin spacing 0.1in (2.54mm)
SW1			DIP SWITCH	package dipswitch-02; channels 1
TFT 3.3v			Generic male header - 3 pins	package THT; variant variant 1; row single; form ♂ (male); pins 3; hole size 1.0mm,0.508mm; pin spacing 0.1in (2.54mm)
TX JMP			Solder Jumper	package sj_2; variant t
WeMos D1 Mini			WeMos D1 Mini	variant variant 1; cpu ESP-8266EX; headers female above
Shopping List
Amount	MN (manufacturer number)	MPN (manufacturer part number)	Part Type	Properties
2			Capacitor	package 1206; variant 1206
1			2.8" SPI TFT Module	variant variant 1; pins 18; chip label LCD; part # MSP2807
3			DIP Switch 4 Position	package dipswitch-04; variant variant 2; channels 4
1			Screw terminal - 4 pins	package THT; pins 4; pin spacing 0.1in (2.54mm); hole size 1.0mm,0.508mm
2			DIP SWITCH	package dipswitch-02; channels 1
1			Adafruit Ultimate GPS v3	variant variant 1; part # Adafruit #746
1			Solder Jumper	package sj_2w; variant w
2			Generic male header - 3 pins	package THT; variant variant 1; row single; form ♂ (male); pins 3; hole size 1.0mm,0.508mm; pin spacing 0.1in (2.54mm)
1			DOIT Esp32 DevKit v1 (30 pins long, 11 pins width)	variant 1; pins 30; part # ESP32S-PIN30
1			Generic double row male header - 16 pins	package THT; row double; form ♂ (male); pins 16; hole size 1.0mm,0.508mm; pin spacing 0.1in (2.54mm)
1			Generic double row male header - 20 pins	package THT; row double; form ♂ (male); pins 20; hole size 1.0mm,0.508mm; pin spacing 0.1in (2.54mm)
1			Generic double row male header - 6 pins	package THT; row double; form ♂ (male); pins 6; hole size 1.0mm,0.508mm; pin spacing 0.1in (2.54mm)
1			Generic male header - 4 pins	package THT; row single; form ♂ (male); pins 4; hole size 1.0mm,0.508mm; pin spacing 0.1in (2.54mm)
3			Red (633nm) LED	package 1206 [SMD]; color Red (633nm)
2			SparkFun - microSD Transflash	variant BOB-00544
1			NRF24L01+ PA LNA	variant variant 2; chip NRF24L01+ PA LNA
2			Solder Jumper	package sj_2; variant t
3			220Ω Resistor	tolerance ±5%; resistance 220Ω; package 1206 [SMD]
1			Generic male header - 14 pins	package THT; row single; form ♂ (male); pins 14; hole size 1.0mm,0.508mm; pin spacing 0.1in (2.54mm)
1			WeMos D1 Mini	variant variant 1; cpu ESP-8266EX; headers female above

Exported with Fritzing 0.9.10- http://fritzing.org

**Comment by IAmOrion** [comment]
[BOM.pdf](https://github.com/IAmOrion/FlipperZeroStuff/files/11569799/BOM.pdf)

Apologies, I've been so busy with house move and life in general I've been outta touch with the flipper stuff, this is a quick and dirty BOM exported directly from Fritzing, should give a good idea though.

***IMPORTANT***  VALUES from the BOM may be incorrect, the CORRECT values and components are marked/labelled on the PCB SilkScreen where relevant

**Comment by LuckyFishGeek** [comment]
> [BOM.pdf](https://github.com/IAmOrion/FlipperZeroStuff/files/11569799/BOM.pdf)
> 
> Apologies, I've been so busy with house move and life in general I've been outta touch with the flipper stuff, this is a quick and dirty BOM exported directly from Fritzing, should give a good idea though.
> 
> _**IMPORTANT**_ VALUES from the BOM may be incorrect, the CORRECT values and components are marked/labelled on the PCB SilkScreen where relevant

Wow, thank you very much for your help and good luck!
Thanks again

**Comment by LuckyFishGeek** [comment]
> [BOM.pdf](https://github.com/IAmOrion/FlipperZeroStuff/files/11569799/BOM.pdf)
> 
> Apologies, I've been so busy with house move and life in general I've been outta touch with the flipper stuff, this is a quick and dirty BOM exported directly from Fritzing, should give a good idea though.
> 
> _**IMPORTANT**_ VALUES from the BOM may be incorrect, the CORRECT values and components are marked/labelled on the PCB SilkScreen where relevant

Sorry to bother you again. . . .

I am still researching the names of some parts, and the names may be different in each region!

It would be even better if you have a diagram of your soldered equipment!

I will reply after you have moved, and I wish you a happy move to your new home.

**Comment by IAmOrion** [comment]
> Sorry to bother you again. . . .
> 
> I am still researching the names of some parts, and the names may be different in each region!
> 
> It would be even better if you have a diagram of your soldered equipment!
> 
> I will reply after you have moved, and I wish you a happy move to your new home.

Thanks, I've already moved (Feb), but just got a lot going on still... I don't have a photo of mine soldered, it was so long ago now, here's some part links though - if I don't link the specific part you're stuck on let me know.  Using AliExpress where possible because it's cheaper but if you don't want to use AliExpress, use the product keywords and search your preferred websites.
These a re NOT the exact links I used but they are the correct items you will need, so do some searching for best prices etc

**FEMALE PCB HEADERS** - 40pin x 10: https://www.aliexpress.com/item/1005001418544370.html 
TFT TOUCH Screen: https://www.aliexpress.com/item/4000631140288.html
DIP Switches - You will need 2 pin and 4 pin: https://www.aliexpress.com/item/10000004737395.html
NRF24L01+PA+LNA: https://www.aliexpress.com/item/1005002866765341.html
Wemos D1 Mini: https://www.aliexpress.com/item/1005004527213280.html
ESP32 30Pin Color: ESP32-CP2102-MICRO:  https://www.aliexpress.com/item/1005004337178335.html
HC-SR04: https://www.aliexpress.com/item/1005001621997017.html
Slide Switches: https://www.aliexpress.com/item/32956747776.html

Adafruit GPS Product ID 746: https://www.adafruit.com/product/746
Sparkfun SD Card Module: https://www.sparkfun.com/products/544

Now, I *highly* recommend using the Female PCB Headers (Cut to size) to mount most of the components like the TFT Screen, the Wemos D1's, the Adafruit GPS, the NRF24L01 etc.  That way if you make a mistake you just makea. new board and then unplug your parts.

The resistors, capacitors and LED are package size "1206" so you can just search any using "1206" as part of the keyword.  Eg: "SMD LED 1206 RED" Do make sure they're "1206" though.   The LEDs and Resistors are totally user choice because there's so many out there, and diff colours use diff values, but as a base value, a 1k resistors will do for any LEDs.

The 2 capacitors used are 10uF and 100nF - again, both are "1206" package size.

Regarding the ESP32 - 30pin variant, there's so many copies and clones out there, there's no telling which will fit as they often have slightly different widths.  It's also been known that seller switch the variant so even giving a link that worked for me may not deliver the same to you (It's very frustrating)

Hope that helps

**Comment by LuckyFishGeek** [comment]
Thank you very much for your kind help

May I have the honor of buying you a cup of coffee?

let me know your paypal account number  ^.^

**Comment by LuckyFishGeek** [comment]
Thank you very much for your kind help
Please allow me to buy you a cup of coffee.

**Comment by IAmOrion** [comment]
Donations are welcome but never expected :) 
My PalPal is in the readme of this main repo
`Want to donate as a "Thank you"? - https://www.paypal.com/paypalme/IAmOrion`
